"""empty message

Revision ID: 2e5c6b0e400c
Revises: e75436ca1e67
Create Date: 2024-03-17 16:51:22.432670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e5c6b0e400c'
down_revision = 'e75436ca1e67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('GroupAdministrators',
    sa.Column('group_uuid', sa.String(length=48), nullable=False),
    sa.Column('user_uuid', sa.String(length=48), nullable=False),
    sa.ForeignKeyConstraint(['group_uuid'], ['Groups.group_uuid'], ),
    sa.ForeignKeyConstraint(['user_uuid'], ['Users.user_uuid'], ),
    sa.PrimaryKeyConstraint('group_uuid', 'user_uuid')
    )
    op.create_table('GroupUsers',
    sa.Column('group_uuid', sa.String(length=48), nullable=False),
    sa.Column('user_uuid', sa.String(length=48), nullable=False),
    sa.ForeignKeyConstraint(['group_uuid'], ['Groups.group_uuid'], ),
    sa.ForeignKeyConstraint(['user_uuid'], ['Users.user_uuid'], ),
    sa.PrimaryKeyConstraint('group_uuid', 'user_uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('GroupUsers')
    op.drop_table('GroupAdministrators')
    # ### end Alembic commands ###
