"""empty message

Revision ID: aeb739f5f180
Revises: eb3cb552250a
Create Date: 2024-03-18 20:11:57.323440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aeb739f5f180'
down_revision = 'eb3cb552250a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ItemPurchasingHistories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ItemPurchasingHistories', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
