"""empty message

Revision ID: be17a4b27fff
Revises: 
Create Date: 2024-03-17 21:31:33.379495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be17a4b27fff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Groups',
    sa.Column('uuid', sa.String(length=48), nullable=False),
    sa.Column('groupname', sa.String(length=48), nullable=False),
    sa.Column('hashed_password', sa.Unicode(), nullable=False),
    sa.Column('display_name', sa.Unicode(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('groupname')
    )
    op.create_table('Users',
    sa.Column('uuid', sa.String(length=48), nullable=False),
    sa.Column('username', sa.String(length=48), nullable=False),
    sa.Column('hashed_password', sa.Unicode(), nullable=False),
    sa.Column('display_name', sa.Unicode(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('username')
    )
    op.create_table('Balances',
    sa.Column('uuid', sa.String(length=48), nullable=False),
    sa.Column('user_uuid', sa.String(length=48), nullable=False),
    sa.Column('group_uuid', sa.String(length=48), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_uuid'], ['Groups.uuid'], ),
    sa.ForeignKeyConstraint(['user_uuid'], ['Users.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('GroupAdministrators',
    sa.Column('user_uuid', sa.String(length=48), nullable=False),
    sa.Column('group_uuid', sa.String(length=48), nullable=False),
    sa.ForeignKeyConstraint(['group_uuid'], ['Groups.uuid'], ),
    sa.ForeignKeyConstraint(['user_uuid'], ['Users.uuid'], ),
    sa.PrimaryKeyConstraint('user_uuid', 'group_uuid')
    )
    op.create_table('GroupMembers',
    sa.Column('user_uuid', sa.String(length=48), nullable=False),
    sa.Column('group_uuid', sa.String(length=48), nullable=False),
    sa.ForeignKeyConstraint(['group_uuid'], ['Groups.uuid'], ),
    sa.ForeignKeyConstraint(['user_uuid'], ['Users.uuid'], ),
    sa.PrimaryKeyConstraint('user_uuid', 'group_uuid')
    )
    op.create_table('ItemGroups',
    sa.Column('uuid', sa.String(length=48), nullable=False),
    sa.Column('group_uuid', sa.String(length=48), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=False),
    sa.Column('color', sa.Unicode(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_uuid'], ['Groups.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('Items',
    sa.Column('uuid', sa.String(length=48), nullable=False),
    sa.Column('item_group_uuid', sa.String(length=48), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=False),
    sa.Column('barcode', sa.Unicode(), nullable=False),
    sa.Column('cost_price', sa.Integer(), nullable=False),
    sa.Column('selling_price', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_group_uuid'], ['ItemGroups.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('ItemExpirationDates',
    sa.Column('uuid', sa.String(length=48), nullable=False),
    sa.Column('item_uuid', sa.String(length=48), nullable=False),
    sa.Column('expiration_date', sa.DateTime(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_uuid'], ['Items.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('ItemThumbnails',
    sa.Column('uuid', sa.String(length=48), nullable=False),
    sa.Column('item_uuid', sa.String(length=48), nullable=False),
    sa.Column('base64', sa.Unicode(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_uuid'], ['Items.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('ItemPurchasingHistories',
    sa.Column('uuid', sa.String(length=48), nullable=False),
    sa.Column('user_uuid', sa.String(length=48), nullable=False),
    sa.Column('item_expiration_date_uuid', sa.String(length=48), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_expiration_date_uuid'], ['ItemExpirationDates.uuid'], ),
    sa.ForeignKeyConstraint(['user_uuid'], ['Users.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ItemPurchasingHistories')
    op.drop_table('ItemThumbnails')
    op.drop_table('ItemExpirationDates')
    op.drop_table('Items')
    op.drop_table('ItemGroups')
    op.drop_table('GroupMembers')
    op.drop_table('GroupAdministrators')
    op.drop_table('Balances')
    op.drop_table('Users')
    op.drop_table('Groups')
    # ### end Alembic commands ###
