"""empty message

Revision ID: e75436ca1e67
Revises: 5bff60a8e658
Create Date: 2024-03-17 13:24:23.460981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e75436ca1e67'
down_revision = '5bff60a8e658'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('user_uuid', sa.String(length=48), nullable=False),
    sa.Column('username', sa.String(length=48), nullable=False),
    sa.Column('hashed_password', sa.Unicode(), nullable=False),
    sa.Column('display_name', sa.Unicode(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_uuid'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Users')
    # ### end Alembic commands ###
