"""empty message

Revision ID: eb3cb552250a
Revises: fbe3d73e17df
Create Date: 2024-03-18 17:47:54.133109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb3cb552250a'
down_revision = 'fbe3d73e17df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_uuid', sa.String(length=48), nullable=False))
        batch_op.create_foreign_key(None, 'Groups', ['group_uuid'], ['uuid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('group_uuid')

    # ### end Alembic commands ###
